import fs from 'node:fs';import path from 'node:path';import {build} from 'vite';import react from '@vitejs/plugin-react';
const root=process.cwd(),out=process.env.PULSE_OUTPUT_DIR?path.resolve(process.env.PULSE_OUTPUT_DIR):path.join(root,'local-output'),local=path.join(root,'.build/offline');fs.mkdirSync(out,{recursive:true});
await import('./scripts/build-methodology.mjs');
for(const name of ['methodology.html','verified-data.csv'])fs.copyFileSync(path.join(root,'docs',name),path.join(out,name));
await build({configFile:false,root,plugins:[react()],resolve:{alias:{'@':root}},define:{'process.env.NODE_ENV':'"production"'},build:{outDir:local,emptyOutDir:true,lib:{entry:path.join(root,'local-entry.tsx'),name:'CityPulse',formats:['iife'],fileName:'pulse'},cssCodeSplit:false,minify:true}});
function walk(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(dir,e.name)):path.join(dir,e.name));}
const files=walk(local),css=files.filter(f=>f.endsWith('.css')).map(f=>fs.readFileSync(f,'utf8')).join('\n'),js=files.filter(f=>f.endsWith('.js')).map(f=>fs.readFileSync(f,'utf8')).join('\n');if(!css||!js)throw new Error('Bundle incomplete');
const html='<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Пульс города — жизнь, работа и деньги</title><link rel="icon" href="data:image/svg+xml,'+encodeURIComponent(fs.readFileSync('public/favicon.svg','utf8'))+'"><style>'+css+'</style></head><body><div id="app"></div><script>'+js.replaceAll('</script','<\\/script')+'</script></body></html>\n';
fs.writeFileSync(path.join(out,'Пульс города.html'),html);fs.writeFileSync(path.join(root,'public','local.html'),html);fs.mkdirSync(path.join(root,'docs'),{recursive:true});fs.writeFileSync(path.join(root,'docs','index.html'),html);fs.writeFileSync(path.join(root,'docs','.nojekyll'),'');fs.writeFileSync(path.join(out,'Как пользоваться.md'),fs.readFileSync('README.md','utf8'));console.log(JSON.stringify({html:path.join(out,'Пульс города.html'),bytes:Buffer.byteLength(html)}));
