"use client";
import {useEffect,useState} from 'react';
import {flushSync} from 'react-dom';
import {Activity,MapPin,Info,SlidersHorizontal,BookOpen,House,Users,LayoutDashboard,Briefcase,ChartNoAxesCombined} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {TooltipProvider,Tooltip,TooltipTrigger,TooltipContent} from '@/components/ui/tooltip';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {cities,money,netSalary,type CityKey} from '@/lib/pulse-data';
import {observation} from '@/lib/real-data';
import {averageObservation} from '@/lib/average-data';
import {AverageSection} from '@/components/pulse-averages';
import {ProfileOverview,WorkSection,PopulationSection} from '@/components/pulse-extended';
import {ObservationCard} from '@/components/pulse-records';
import {HousingSection} from '@/components/pulse-sections';
import {SourceContent} from '@/components/pulse-sources';
const views=[{id:'overview',name:'Обзор и бюджет',icon:LayoutDashboard},{id:'work',name:'Работа и зарплаты',icon:Briefcase},{id:'population',name:'Население',icon:Users},{id:'housing',name:'Жильё',icon:House}];
export default function Home(){
 const [city,setCity]=useState<CityKey>('spb'),[view,setView]=useState('overview'),[sources,setSources]=useState(false),[edit,setEdit]=useState(true),[basis,setBasis]=useState('net'),[custom,setCustom]=useState<Record<string,number>>({}),[salaryPreset,setSalaryPreset]=useState(false);
 const averageSalary=averageObservation(city,'salary');
 const d=cities[city],rentData=observation(city,'rent1'),income=custom.income,net=income!=null&&income>0?(basis==='gross'?netSalary(income):income):null,rent=custom.rent??rentData?.value;
 const fields=[{id:'rent',name:'Аренда',v:rent},{id:'utilities',name:'ЖКХ',v:custom.utilities},{id:'food',name:'Продукты',v:custom.food},{id:'transport',name:'Транспорт',v:custom.transport},{id:'connection',name:'Связь и интернет',v:custom.connection}];
 const ready=net!=null&&fields.every(f=>f.v!=null),costs=ready?fields.reduce((a,f)=>a+f.v!,0):null,left=ready?net!-costs!:null;
 const expenses=[{n:'Налог',v:income!=null&&net!=null?income-net:0,c:'#a8b4c6'},{n:'Аренда',v:rent??0,c:'#3a52d5'},{n:'ЖКХ',v:custom.utilities??0,c:'#6983e6'},{n:'Продукты',v:custom.food??0,c:'#99adef'},{n:'Транспорт и связь',v:(custom.transport??0)+(custom.connection??0),c:'#ccd6f6'},{n:'Остаток',v:left??0,c:'#12243b'}];
 useEffect(()=>{type MC={registerTool:(t:unknown,o:{signal:AbortSignal})=>unknown};const mc=(document as Document&{modelContext?:MC}).modelContext;if(!mc)return;const life=new AbortController();const tool={name:'configure_city_budget',title:'Рассчитать личный бюджет',description:'Выбрать город и рассчитать личный месячный бюджет из введённых сумм. Не меняет статистику города и не сохраняет данные вне страницы.',inputSchema:{type:'object',properties:{city:{type:'string',enum:['spb','krd']},basis:{type:'string',enum:['gross','net']},income:{type:'number',exclusiveMinimum:0,maximum:10000000},rent:{type:'number',minimum:0,maximum:10000000},utilities:{type:'number',minimum:0,maximum:10000000},food:{type:'number',minimum:0,maximum:10000000},transport:{type:'number',minimum:0,maximum:10000000},connection:{type:'number',minimum:0,maximum:10000000}},required:['city','basis','income','rent','utilities','food','transport','connection'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const a=input as Record<string,unknown>,keys=['income','rent','utilities','food','transport','connection'];if(!a||!['spb','krd'].includes(String(a.city))||!['gross','net'].includes(String(a.basis))||!keys.every(k=>typeof a[k]==='number'&&Number.isFinite(a[k])&&(a[k] as number)>=0&&(a[k] as number)<=10000000)||(a.income as number)<=0||Object.keys(a).some(k=>!['city','basis',...keys].includes(k)))throw new Error('Некорректный сценарий');const custom=Object.fromEntries(keys.map(k=>[k,a[k] as number])),net=a.basis==='gross'?netSalary(custom.income):custom.income,cost=keys.filter(k=>k!=='income').reduce((s,k)=>s+custom[k],0);flushSync(()=>{setCity(a.city as CityKey);setBasis(a.basis as string);setCustom(custom);setSalaryPreset(false);setView('overview');setEdit(true)});return{city:a.city,net_income:net,expenses:cost,remainder:net-cost,status:'user_scenario',quality:'D'}}};try{Promise.resolve(mc.registerTool(tool,{signal:life.signal})).catch(()=>{})}catch{}return()=>life.abort()},[]);
 return <TooltipProvider delayDuration={200}><Tabs value={view} onValueChange={v=>{setView(v);window.scrollTo({top:0,behavior:'instant'})}} className="app-shell"><header className="topbar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setView('overview');window.scrollTo(0,0)}} aria-label="Пульс города — главная"><span className="brand-mark"><Activity size={24}/></span><strong>пульс города<span>ЖИЗНЬ, РАБОТА И ДЕНЬГИ</span></strong></a><div className="city-control"><MapPin size={17}/><Tabs value={city} onValueChange={v=>{setCity(v as CityKey);setCustom({});setBasis('net');setSalaryPreset(false)}}><TabsList className="city-tabs"><TabsTrigger value="spb">Санкт-Петербург</TabsTrigger><TabsTrigger value="krd">Краснодар</TabsTrigger></TabsList></Tabs></div><button className="text-button source-button" onClick={()=>setSources(true)}><BookOpen size={17}/>Источники и пояснения</button></header><div className="shell-body"><aside className="sidebar"><p className="nav-label">НА ЭТОЙ СТРАНИЦЕ</p><TabsList className="side-nav">{views.map(v=><TabsTrigger key={v.id} value={v.id} className="nav-item"><v.icon size={19}/>{v.name}</TabsTrigger>)}</TabsList><div className="side-bottom"><span className="edition">ФИКСИРОВАННЫЙ СНИМОК</span><p>Источники и даты<br/>у каждого показателя.</p><button className="text-button" onClick={()=>setSources(true)}>Об источниках<Info size={15}/></button></div></aside><main className="workspace"><div className="context-bar"><span><MapPin size={14}/>{d.name}<span className="divider">/</span>Жизнь и работа</span><span className="panel-tag">Фиксированные данные · 2024–2026</span></div><div className="real-notice"><Info size={16}/><p>Фиксированные данные без обновлений. Показатели относятся к разным периодам: дата, территория и источник указаны у каждого числа.</p><button onClick={()=>setSources(true)}>Источники</button></div>
 <TabsContent value="overview"><div className="page-heading"><div><p className="eyebrow">ЖИЗНЬ И РАБОТА</p><h1>Жизнь и работа в {d.locative}</h1><p className="subheading">Зарплаты, поиск работы, население и жильё. Расчёт бюджета — на ваших суммах.</p></div><span className="period-note">Проверка источников<br/><strong>4–7 октября 2026</strong></span></div><ProfileOverview city={city}/><div className="section-heading housing-overview"><h2>Средние цены жилья</h2></div><div className="kpi-grid overview-housing"><ObservationCard data={rentData} label="Средняя аренда 1-к"/><ObservationCard data={observation(city,'sqm')} label="Средняя цена м²"/></div>
 <section id="personal-budget" className="panel budget-panel"><div className="section-heading"><div><p className="eyebrow">ОТ ДОХОДА ДО СВОБОДНЫХ ДЕНЕГ</p><h2>Что останется в вашем бюджете</h2></div><button className="outline-button" onClick={()=>setEdit(!edit)}><SlidersHorizontal size={16}/>{edit?'Свернуть настройки':'Настроить сценарий'}</button></div><div className="scenario-label"><Users size={15}/>Один человек<span>·</span>Аренда 1-к<span>·</span>Ваши расходы</div>{edit&&<div className="scenario-editor"><label>Ваш доход, ₽/мес<input type="number" min="0" max="10000000" value={income??''} placeholder="Введите доход" onChange={e=>{setSalaryPreset(false);setCustom({...custom,income:e.target.value===''?undefined as unknown as number:Math.max(0,Math.min(10000000,Number(e.target.value)))})}}/></label><label>Доход указан<NativeSelect value={basis} onChange={e=>{setBasis(e.target.value);setSalaryPreset(false)}} aria-label="Доход до налога или на руки"><NativeSelectOption value="net">На руки</NativeSelectOption><NativeSelectOption value="gross">До налога</NativeSelectOption></NativeSelect></label>{fields.map(f=><label key={f.id}>{f.name}, ₽/мес<input type="number" min="0" max="10000000" value={f.v??''} placeholder="Укажите расходы" onChange={e=>setCustom({...custom,[f.id]:e.target.value===''?undefined as unknown as number:Math.max(0,Math.min(10000000,Number(e.target.value)))})}/>{f.id==='rent'&&custom.rent===undefined&&rentData&&<small>Средняя цена предложений · {rentData.period}</small>}</label>)}<button className="outline-button" onClick={()=>{setCustom({});setBasis('net');setSalaryPreset(false)}}>Очистить бюджет</button></div>}
 {salaryPreset&&averageSalary&&<p className="budget-preset">В доход подставлена средняя начисленная зарплата: {averageSalary.period.toLowerCase()}, {averageSalary.geo}. Расходы укажите самостоятельно. Этот сценарий не описывает бюджет типичного жителя.</p>}{ready?<><div className="budget-summary"><div><span>Чистый доход</span><strong>{money(net!)} ₽</strong></div><div className="budget-result"><span>{left!>=0?'Остаётся на ваши планы':'Расходы превышают доход'}</span><strong>{money(Math.abs(left!))} ₽</strong></div></div><div className="expense-bar" aria-label="Структура личного месячного бюджета">{expenses.filter(s=>s.v>0).map(s=><Tooltip key={s.n}><TooltipTrigger asChild><div style={{flex:s.v,background:s.c}} tabIndex={0}/></TooltipTrigger><TooltipContent>{s.n}: {money(s.v)} ₽</TooltipContent></Tooltip>)}</div><div className="expense-legend">{expenses.map(s=><div key={s.n}><span><i style={{background:s.c}}/>{s.n}</span><strong>{money(s.v)} ₽</strong></div>)}</div></>:<p className="budget-empty">Введите положительный доход и все расходы. Нулевой расход допустим, если вы указали его явно. Без этих значений остаток не рассчитывается.</p>}<p className="model-note"><Info size={14}/>Ваш расчёт: введённые суммы{custom.rent===undefined&&rentData?' и средняя рыночная аренда':''}. Это не доход типичного жителя. Для дохода до налога используется годовая прогрессивная шкала НДФЛ, без вычетов.</p></section>
 <div className="two-columns"><section className="panel"><h2>Что подтверждено</h2><p className="section-copy">Средние ставки аренды и цена м² опубликованы в сентябре 2026 года. Стоимость однокомнатной квартиры — в январе. Это данные ЦИАН по каждому городу. Точный день замера и размер выборки квартир не раскрыты.</p><button className="outline-button" onClick={()=>setSources(true)}>Проверить первоисточники</button></section><section className="panel"><h2>Как читать эти цены</h2><p className="section-copy">Средняя цена не означает, что большинство квартир стоят именно столько. Аренда и цена м² относятся к объявлениям. Для январской стоимости 1-к источник не уточняет, использовал ли он объявления или совершённые сделки.</p><p className="section-copy">Официальные зарплаты описывают работников организаций, а цены жилья — рынок объявлений. Периоды и охват различаются. Средние фактические расходы жителя не подтверждены для этого выпуска: свои суммы укажите в калькуляторе.</p></section></div></TabsContent>
 <TabsContent value="work"><div className="page-heading"><div><p className="eyebrow">{d.name.toUpperCase()}</p><h1>Работа и зарплаты</h1><p className="subheading">Фактический заработок, предложения работодателей и безработица — отдельные показатели.</p></div></div><WorkSection city={city}/><AverageSection city={city} onUseSalary={value=>{setCustom({...custom,income:value});setBasis('gross');setSalaryPreset(true);setEdit(true);setView('overview');window.scrollTo({top:0,behavior:'instant'});setTimeout(()=>document.getElementById('personal-budget')?.scrollIntoView({behavior:'smooth',block:'start'}),0)}}/></TabsContent><TabsContent value="population"><div className="page-heading"><div><p className="eyebrow">{d.name.toUpperCase()}</p><h1>Население</h1><p className="subheading">Численность и изменение населения. Территория и дата — у каждого показателя.</p></div></div><PopulationSection city={city}/></TabsContent><TabsContent value="housing"><div className="page-heading"><div><p className="eyebrow">{d.name.toUpperCase()}</p><h1>Подробнее о жилье</h1><p className="subheading">Средние цены и их соотношение с вашим доходом.</p></div></div><HousingSection city={city} net={net}/></TabsContent><footer className="footer"><span>Пульс города · фиксированный снимок</span><a href="methodology.html" target="_blank" rel="noreferrer">Методика и источники ↗</a><span>Данные проверены 4–7 октября 2026</span></footer></main></div><Sheet open={sources} onOpenChange={setSources}><SheetContent className="source-sheet"><SheetHeader><SheetTitle>Источники и пояснения</SheetTitle><SheetDescription>Первоисточники, периоды и ограничения</SheetDescription></SheetHeader><SourceContent/></SheetContent></Sheet></Tabs></TooltipProvider>
}
